spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #阿里oss配置
    alicloud:
      access-key: 使用自己的
      secret-key: 使用自己的
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-chengs
server:
  port: 14000