spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #阿里oss配置
    alicloud:
      access-key: LTAI5tGiAaoP7sTWXnVd7z95
      secret-key: 3glPaqvKbo8m5Jm50B42HJYmyjTSFf
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-chengs
server:
  port: 14000